# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

    app.doctrine.hash_password_listener:
        class: ExchangeBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.security.login_form_authenticator:
        class: ExchangeBundle\Security\LoginTypeAuthenticator
        autowire: true

    app.wallet_service:
        class: ExchangeBundle\Services\WalletService

    app.check_service:
        class: ExchangeBundle\Services\CheckApiService
